/** @format */

// models/aiMarketingCampaign.js

const mongoose = require("mongoose");
const { ObjectId } = mongoose.Schema;

/**
 * Small reusable schema for ad metrics
 * (used at campaign level + per platform).
 */
const metricsSchema = new mongoose.Schema(
	{
		impressions: { type: Number, default: 0 },
		clicks: { type: Number, default: 0 },
		ctr: { type: Number, default: 0 }, // convenience cache
		cost: { type: Number, default: 0 }, // in campaign.currency
		cpc: { type: Number, default: 0 },
		conversions: { type: Number, default: 0 },
		conversionRate: { type: Number, default: 0 },
		revenue: { type: Number, default: 0 }, // from GA / orders
		roas: { type: Number, default: 0 },
		addToCarts: { type: Number, default: 0 },
		purchases: { type: Number, default: 0 },
	},
	{ _id: false }
);

/**
 * Metrics specifically from Google Analytics (GA4/etc)
 */
const gaMetricsSchema = new mongoose.Schema(
	{
		sessions: { type: Number, default: 0 },
		users: { type: Number, default: 0 },
		newUsers: { type: Number, default: 0 },
		engagedSessions: { type: Number, default: 0 },
		bounceRate: { type: Number, default: 0 },
		avgSessionDurationSeconds: { type: Number, default: 0 },
		transactions: { type: Number, default: 0 },
		transactionRevenue: { type: Number, default: 0 },
	},
	{ _id: false }
);

/**
 * Generic text variant (headlines, primary text, descriptions, etc.)
 * Usually generated by OpenAI or edited by user.
 */
const textVariantSchema = new mongoose.Schema(
	{
		label: { type: String, trim: true }, // e.g. "Primary Text A"
		platform: {
			type: String,
			enum: ["google", "facebook", "universal"],
			default: "universal",
		},
		text: { type: String, required: true },
		language: { type: String, default: "en" },
		tone: { type: String, default: "neutral" },
		generatedBy: {
			type: String,
			enum: ["ai", "user"],
			default: "ai",
		},
		performanceLabel: {
			type: String,
			enum: ["unknown", "learning", "winner", "loser"],
			default: "unknown",
		},
	},
	{ _id: false }
);

/**
 * Image asset (mostly based on existing product images)
 */
const imageAssetSchema = new mongoose.Schema(
	{
		product: { type: ObjectId, ref: "Product" },
		url: { type: String, required: true },
		altText: { type: String, default: "" },
		aspectRatio: { type: String, default: "" }, // e.g. "1.91:1", "4:5"
		source: {
			type: String,
			enum: ["product_image", "uploaded", "generated"],
			default: "product_image",
		},
		generatedBy: {
			type: String,
			enum: ["ai", "user", "system"],
			default: "system",
		},
		tags: [String], // e.g. ["lifestyle", "closeup"]
	},
	{ _id: false }
);

/**
 * Video asset (RunwayML or uploaded)
 */
const videoAssetSchema = new mongoose.Schema(
	{
		product: { type: ObjectId, ref: "Product" },
		url: { type: String }, // final video URL
		thumbnailUrl: { type: String },
		durationSeconds: { type: Number, default: 0 },
		aspectRatio: { type: String, default: "" },
		source: {
			type: String,
			enum: ["runwayml", "uploaded"],
			default: "runwayml",
		},
		runwayJobId: { type: String }, // to poll RunwayML
		status: {
			type: String,
			enum: ["pending", "generating", "ready", "error"],
			default: "pending",
		},
		errorMessage: { type: String, default: "" },
		styleTags: [String], // e.g. ["product_promo", "ugc_style"]
	},
	{ _id: false }
);

/**
 * Background music track (Jamendo, etc.)
 */
const musicTrackSchema = new mongoose.Schema(
	{
		jamendoTrackId: { type: String },
		name: { type: String },
		artistName: { type: String },
		streamUrl: { type: String },
		downloadUrl: { type: String },
		license: { type: String },
		durationSeconds: { type: Number, default: 0 },
		bpm: { type: Number, default: 0 },
		moodTags: [String], // e.g. ["uplifting", "energetic"]
	},
	{ _id: false }
);

/**
 * An individual audit event. This is what will be pushed into
 * campaign.auditLogs[] every ~3 hours.
 */
const auditLogSchema = new mongoose.Schema(
	{
		timestamp: { type: Date, default: Date.now },
		triggeredBy: {
			type: String,
			enum: ["system_cron", "user", "ai"],
			default: "system_cron",
		},
		eventType: {
			type: String,
			enum: [
				"campaign_created",
				"assets_generated",
				"campaign_published",
				"audit",
				"optimization",
				"recreated",
				"paused",
				"resumed",
				"cancelled",
				"error",
			],
			default: "audit",
		},
		summary: { type: String, trim: true },

		// High‑level snapshot of metrics at that time
		metricsSnapshot: metricsSchema,

		platformMetrics: {
			googleAds: metricsSchema,
			facebookAds: metricsSchema,
			googleAnalytics: gaMetricsSchema,
		},

		decision: {
			action: {
				type: String,
				enum: [
					"none",
					"increase_budget",
					"decrease_budget",
					"pause_underperforming_ads",
					"shift_budget_between_platforms",
					"create_new_creatives",
					"cancel_and_recreate",
					"fix_error",
				],
				default: "none",
			},
			reason: { type: String },
			changes: {
				// Example deltas (optional – controller will fill as needed)
				previousDailyBudget: Number,
				newDailyBudget: Number,
				budgetChangePercent: Number,

				previousBid: Number,
				newBid: Number,

				pausedAdIds: [String],
				createdAdIds: [String],
				notes: String,
			},
		},

		error: {
			message: String,
			code: String,
			raw: mongoose.Schema.Types.Mixed,
		},
	},
	{ _id: false }
);

/**
 * Main AI Marketing Campaign schema
 */
const aiMarketingCampaignSchema = new mongoose.Schema(
	{
		// ------------- BASIC META / OWNER -------------

		name: {
			type: String,
			required: true,
			trim: true,
			maxlength: 200,
		},
		description: {
			type: String,
			trim: true,
		},

		createdBy: {
			type: ObjectId,
			ref: "User",
			required: true,
		},
		store: {
			type: ObjectId,
			ref: "StoreManagement",
			default: null,
		},

		// Explicit product selection for this campaign
		products: [
			{
				type: ObjectId,
				ref: "Product",
				required: true,
			},
		],

		// If campaign is specialized for POD products
		isPODCampaign: {
			type: Boolean,
			default: false,
		},

		// E.g. "sales", "traffic", "brand_awareness", "video_views"
		objective: {
			type: String,
			enum: [
				"sales",
				"traffic",
				"leads",
				"brand_awareness",
				"engagement",
				"video_views",
				"app_promotion",
				"other",
			],
			default: "sales",
		},

		// ------------- BUDGET & SCHEDULE -------------

		currency: {
			type: String,
			default: "USD",
		},

		budget: {
			// User‑provided interval [min, max]
			dailyMin: { type: Number, required: true },
			dailyMax: { type: Number, required: true },
			currentDaily: { type: Number, default: 0 }, // set by the AI within [min,max]
			lifetimeCap: { type: Number, default: 0 }, // optional
			biddingStrategy: {
				type: String,
				default: "auto",
			}, // "auto" vs "manual" logic in controller
			pacing: {
				type: String,
				enum: ["standard", "accelerated"],
				default: "standard",
			},
		},

		schedule: {
			startDate: { type: Date, required: true },
			endDate: { type: Date }, // optional – open‑ended campaigns
			timeZone: { type: String, default: "UTC" },

			// What to do when endDate is reached
			endBehaviour: {
				type: String,
				enum: ["pause", "archive", "none"],
				default: "pause",
			},
		},

		// ------------- TARGETING / AUDIENCE -------------

		targetAudience: {
			locations: [
				{
					country: String, // "US", "EG", etc.
					region: String,
					city: String,
				},
			],
			languages: [String], // e.g. ["en", "ar"]
			ageRange: {
				min: { type: Number, default: 18 },
				max: { type: Number, default: 65 },
			},
			genders: [
				{
					type: String,
					enum: ["male", "female", "unknown", "all", "unisex"],
					default: "all",
				},
			],
			interests: [String], // high‑level interest tags
			behaviors: [String],
			keywords: [String],

			remarketing: {
				websiteVisitors: { type: Boolean, default: false },
				productViewers: { type: Boolean, default: false },
				cartAbandoners: { type: Boolean, default: false },
				pastPurchasers: { type: Boolean, default: false },
			},
		},

		// ------------- CREATIVE STRATEGY & ASSETS -------------

		creativeStrategy: {
			language: { type: String, default: "en" },
			toneOfVoice: {
				type: String,
				default: "friendly", // used when calling OpenAI
			},
			useProductImages: { type: Boolean, default: true },
			useLifestyleMockups: { type: Boolean, default: true },
			variantsPerPlatform: { type: Number, default: 3 }, // how many ad variants AI should create
			preferVideoForPOD: { type: Boolean, default: true },
		},

		copy: {
			primaryTexts: [textVariantSchema],
			headlines: [textVariantSchema],
			descriptions: [textVariantSchema],
			callToActions: [String], // e.g. ["SHOP_NOW", "LEARN_MORE"]
		},

		images: [imageAssetSchema],
		videos: [videoAssetSchema],
		musicTracks: [musicTrackSchema],

		// ------------- PLATFORM CONFIG / STATE -------------

		platforms: {
			googleAds: {
				enabled: { type: Boolean, default: false },
				customerId: { type: String }, // Google Ads customer ID
				campaignId: { type: String }, // Google Ads campaign ID
				// if you use ad groups or asset groups (e.g. PMAX)
				adGroupIds: [String],
				campaignType: {
					type: String,
					enum: [
						"search",
						"display",
						"shopping",
						"performance_max",
						"video",
						"other",
					],
				},
				status: {
					type: String,
					enum: [
						"not_created",
						"creating",
						"active",
						"paused",
						"ended",
						"error",
					],
					default: "not_created",
				},
				lastSyncAt: { type: Date },
			},

			facebookAds: {
				enabled: { type: Boolean, default: false },
				adAccountId: { type: String },
				campaignId: { type: String },
				adSetIds: [String],
				pixelId: { type: String },
				objective: { type: String }, // raw FB objective if needed
				status: {
					type: String,
					enum: [
						"not_created",
						"creating",
						"active",
						"paused",
						"ended",
						"error",
					],
					default: "not_created",
				},
				lastSyncAt: { type: Date },
			},
		},

		// ------------- ANALYTICS / PERFORMANCE -------------

		analytics: {
			aggregated: metricsSchema,
			byPlatform: {
				googleAds: metricsSchema,
				facebookAds: metricsSchema,
			},
			googleAnalytics: gaMetricsSchema,
			lastRefreshedAt: { type: Date },
		},

		// ------------- AUTOMATION / AI BEHAVIOUR -------------

		automationSettings: {
			enabled: { type: Boolean, default: true },
			auditIntervalHours: { type: Number, default: 3 }, // cron every 3h
			minImpressionsBeforeOptimize: { type: Number, default: 500 },
			minClicksBeforeOptimize: { type: Number, default: 20 },

			// Targets – AI tries to move towards these
			targetCPA: { type: Number }, // cost per acquisition
			targetROAS: { type: Number }, // 4.0 == 400%
			maxCPC: { type: Number },

			learningPhaseHours: { type: Number, default: 24 },

			// Controls for aggressive behaviour
			allowCampaignRecreation: { type: Boolean, default: true },
			maxRecreationCount: { type: Number, default: 3 },
			minHoursBetweenRecreations: { type: Number, default: 24 },
		},

		lifecycle: {
			status: {
				type: String,
				enum: [
					"draft",
					"active",
					"paused",
					"cancelled_by_ai",
					"cancelled_by_user",
					"completed",
				],
				default: "draft",
			},
			statusReason: { type: String }, // human‑readable reason
			lastStatusChangeAt: { type: Date },
			lastAuditAt: { type: Date },
			nextAuditAt: { type: Date }, // used by cron to find campaigns to audit
			lastErrorCode: { type: String },
			lastErrorMessage: { type: String },
			totalRecreationCount: { type: Number, default: 0 },
			lastRecreatedAt: { type: Date },
		},

		// ------------- INTEGRATION CONFIG -------------

		/**
		 * NOTE:
		 * In production you normally DO NOT want to store raw secrets here.
		 * You can:
		 *  - store only account IDs and use global env credentials, or
		 *  - encrypt any tokens you store in these fields.
		 */
		integrationConfig: {
			openai: {
				model: { type: String, default: "gpt-5.1" },
				useEnvToken: { type: Boolean, default: true },
			},
			googleAds: {
				useEnvCredentials: { type: Boolean, default: true },
				// if you really need per‑user tokens, encrypt & store:
				refreshToken: { type: String },
				accessTokenExpiresAt: { type: Date },
				loginCustomerId: { type: String }, // MCC
			},
			facebookAds: {
				useEnvCredentials: { type: Boolean, default: true },
				accessToken: { type: String },
				tokenExpiresAt: { type: Date },
				pageId: { type: String },
			},
			googleAnalytics: {
				propertyId: { type: String },
				measurementId: { type: String },
				apiSecret: { type: String }, // again: ideally not raw
			},
			runwayml: {
				useEnvToken: { type: Boolean, default: true },
				apiKey: { type: String },
			},
			jamendo: {
				useEnvCredentials: { type: Boolean, default: true },
				clientId: { type: String },
				clientSecret: { type: String },
			},
		},

		// ------------- AUDIT LOGS (CORE REQUIREMENT) -------------

		auditLogs: [auditLogSchema],

		// ------------- MISC NOTES -------------

		notes: { type: String },
	},
	{ timestamps: true, minimize: false }
);

// Helpful indexes
aiMarketingCampaignSchema.index({
	"lifecycle.status": 1,
	"lifecycle.nextAuditAt": 1,
});

aiMarketingCampaignSchema.index({ store: 1, createdBy: 1 });
aiMarketingCampaignSchema.index({ isPODCampaign: 1 });

module.exports = mongoose.model(
	"AiMarketingCampaign",
	aiMarketingCampaignSchema
);
